# Generated by Django 5.0.4 on 2024-05-01 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allmed_api', '0002_remove_patient_user_alter_user_pin_delete_doctor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='specialization',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
