export const SPECIALIZATIONS = [
    'Interná medicína',
    'Kardiológia',
    'Stomatológia',
    'Neurológia',
    'Pediatria',
    'Ortopédia',
    'Gynekológia',
    'Dermatológia',
    'Anestéziológia',
    'Rádiológia',
    'Patológia',
    'Onkológia',
    'Urológia',
    'Endokrinológia',
    'Reumatológia',
    'Gastroenterológia',
    'Nefrológia',
    'Hematológia',
    'Pneumológia',
    'Otorinolaryngológia',
    'Psychiatria',
    'Všeobecná chirurgia',
    'Neurochirurgia',
];